import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const sessionKey = 'ivy-session';
const getSession = () => JSON.parse(localStorage.getItem(sessionKey) || 'null');
async function refreshSession(session) {
  const response = await fetch('/api/auth/refresh', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ refresh_token: session.refresh_token }) });
  const data = await response.json().catch(() => ({}));
  if (!response.ok || !data.access_token) throw new Error(data.detail || 'Your session has expired. Please sign in again.');
  localStorage.setItem(sessionKey, JSON.stringify(data));
  return data;
}
async function request(path, options = {}, retried = false) {
  const session = getSession();
  const response = await fetch(`/api/${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(session?.access_token ? { Authorization: `Bearer ${session.access_token}` } : {}), ...options.headers } });
  const data = await response.json().catch(() => ({}));
  if (response.status === 401 && session?.refresh_token && !retried) {
    await refreshSession(session);
    return request(path, options, true);
  }
  if (!response.ok) throw new Error(Array.isArray(data.detail) ? data.detail.map(x => x.msg).join(', ') : data.detail || 'Request failed');
  return data;
}
const money = value => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value || 0);
const area = value => value ? `${Number(value).toLocaleString('en-IN')} sq ft` : '—';

function Login({ onLogin }) {
  const [email, setEmail] = useState('demo1@ivy.homes'), [password, setPassword] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  async function submit(e) { e.preventDefault(); setBusy(true); setError(''); try { const data = await request('auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); localStorage.setItem(sessionKey, JSON.stringify(data)); onLogin(data); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  return <main className="login"><section><span className="eyebrow">IVY HOMES</span><h1>Find a place that feels right.</h1><p>Browse verified homes, rentals and new projects in your city.</p><form onSubmit={submit}><label>Email<input value={email} onChange={e => setEmail(e.target.value)} type="email" /></label><label>Password<input value={password} onChange={e => setPassword(e.target.value)} type="password" required /></label>{error && <p className="error">{error}</p>}<button disabled={busy}>{busy ? 'Signing in…' : 'Sign in'}</button></form><small>Use one of the provided Ivy Homes demo accounts.</small></section></main>;
}
function Card({ item, onOpen, saved, onSave }) { return <article className="card"><div className="photo"><span>{item.bedroom || '—'} BHK</span><button className="heart" onClick={() => onSave(item.listing_id)}>{saved ? '♥' : '♡'}</button></div><div className="card-body"><p className="muted">{item.locality} · {item.property_type}</p><h3>{item.apartment_name || item.title || 'A beautiful home'}</h3><strong>{money(item.price)}</strong><p>{area(item.carpet_area)} · {item.furnishing || 'Details available'}</p><button className="link" onClick={() => onOpen(item)}>View details →</button></div></article>; }
function Browse({ kind, saved, onSave, onOpen }) {
  const [data, setData] = useState({ results: [], total: 0, has_more: false }), [loading, setLoading] = useState(true), [error, setError] = useState(''), [filters, setFilters] = useState({ locality: '', bedroom: '', furnishing: '', min_price: '', max_price: '' }), [offset, setOffset] = useState(0);
  const title = kind === 'listings' ? 'Homes for sale' : kind === 'rentals' ? 'Homes for rent' : 'New projects';
  useEffect(() => { let ignore = false; async function load() { setLoading(true); setError(''); const serverQuery = new URLSearchParams(); if (filters.locality) serverQuery.set('locality', filters.locality); if (filters.bedroom) serverQuery.set('bhk', filters.bedroom); const needsLocalFiltering = Boolean(filters.furnishing || filters.min_price || filters.max_price); try { if (!needsLocalFiltering) { serverQuery.set('limit', '12'); serverQuery.set('offset', String(offset)); const page = await request(`${kind}?${serverQuery}`); if (!ignore) setData(page); return; } const all = []; let apiOffset = 0; while (true) { const query = new URLSearchParams(serverQuery); query.set('limit', '50'); query.set('offset', String(apiOffset)); const page = await request(`${kind}?${query}`); all.push(...(page.results || [])); if (!page.has_more) break; apiOffset += page.count; } const filtered = all.filter(item => (!filters.furnishing || item.furnishing === filters.furnishing) && (!filters.min_price || item.price >= Number(filters.min_price)) && (!filters.max_price || item.price <= Number(filters.max_price))); if (!ignore) setData({ results: filtered.slice(offset, offset + 12), total: filtered.length, has_more: offset + 12 < filtered.length }); } catch (e) { if (!ignore) setError(e.message); } finally { if (!ignore) setLoading(false); } } load(); return () => { ignore = true; }; }, [kind, offset, JSON.stringify(filters)]);
  function change(key, value) { setOffset(0); setFilters({ ...filters, [key]: value }); }
  return <><section className="hero"><span className="eyebrow">DISCOVER</span><h2>{title}</h2><p>{data.total?.toLocaleString('en-IN') || '…'} opportunities, chosen for you.</p></section>{kind !== 'projects' && <section className="filters"><input placeholder="Locality" value={filters.locality} onChange={e => change('locality', e.target.value)} /><select value={filters.bedroom} onChange={e => change('bedroom', e.target.value)}><option value="">Any BHK</option>{[1,2,3,4,5].map(n => <option key={n} value={n}>{n} BHK</option>)}</select><select value={filters.furnishing} onChange={e => change('furnishing', e.target.value)}><option value="">Any furnishing</option><option>unfurnished</option><option>semi-furnished</option><option>fully-furnished</option></select><input type="number" placeholder="Min price" value={filters.min_price} onChange={e => change('min_price', e.target.value)} /><input type="number" placeholder="Max price" value={filters.max_price} onChange={e => change('max_price', e.target.value)} /></section>}{error ? <p className="error">{error}</p> : loading ? <p className="loading">Loading homes…</p> : <><section className="grid">{data.results.map(item => kind === 'projects' ? <article className="card project" key={item.project_id}><div className="photo"><span>{item.project_status}</span></div><div className="card-body"><p className="muted">{item.locality}</p><h3>{item.apartment_name}</h3><strong>{money(item.price_min)} – {money(item.price_max)}</strong><p>{area(item.min_area_sqft)} – {area(item.max_area_sqft)}</p><p>{item.total_units} homes · {item.developer_name}</p></div></article> : <Card key={item.listing_id} item={item} saved={saved.includes(item.listing_id)} onSave={onSave} onOpen={onOpen} />)}</section><div className="pager"><button disabled={!offset} onClick={() => setOffset(Math.max(0, offset - 12))}>← Previous</button><span>{offset + 1}–{Math.min(offset + 12, data.total)} of {data.total}</span><button disabled={!data.has_more} onClick={() => setOffset(offset + 12)}>Next →</button></div></>}</>;
}
function Detail({ item, close, saved, onSave }) { return <section className="detail"><button className="link" onClick={close}>← Back to results</button><div className="detail-hero"><div><span className="eyebrow">{item.locality}</span><h2>{item.apartment_name}</h2><p>{item.bedroom} BHK {item.property_type} · {item.furnishing}</p><h1>{money(item.price)}</h1><button onClick={() => onSave(item.listing_id)}>{saved ? '♥ Saved' : '♡ Save listing'}</button></div><div className="stat-grid"><div><b>{area(item.carpet_area)}</b><span>Carpet area</span></div><div><b>{item.bathroom || '—'}</b><span>Bathrooms</span></div><div><b>{item.floor || '—'} / {item.total_floors || '—'}</b><span>Floor</span></div><div><b>{item.is_verified ? 'Verified' : 'Listed'}</b><span>Status</span></div></div></div><section className="description"><h3>About this home</h3><p>{item.description || 'Contact the seller for more details about this property.'}</p><p className="muted">Listed by {item.posted_by_name || item.posted_by} · {new Date(item.posted_at).toLocaleDateString('en-IN')}</p></section></section>; }
function Insights() { const [data, setData] = useState(null), [error, setError] = useState(''); useEffect(() => { request('analytics/summary').then(setData).catch(e => setError(e.message)); }, []); if (error) return <p className="error">{error}</p>; if (!data) return <p className="loading">Loading market insights…</p>; return <><section className="hero"><span className="eyebrow">MARKET PULSE</span><h2>City insights</h2><p>A clear view of what’s happening in your market.</p></section><section className="metrics"><div><span>Listings</span><b>{data.total_listings?.toLocaleString('en-IN')}</b></div><div><span>Median price</span><b>{money(data.median_price)}</b></div><div><span>Median ₹/sq ft</span><b>{money(data.median_price_per_sqft)}</b></div></section><section className="insight-list"><h3>By locality</h3>{(data.by_locality || []).slice(0, 12).map(x => <div key={x.locality}><span>{x.locality}</span><span>{x.count} listings</span><b>{money(x.median_price)}</b></div>)}</section></>; }
function Saved({ saved, onSave, onOpen }) { const [items, setItems] = useState(null), [error, setError] = useState(''); useEffect(() => { request('favourites').then(x => setItems(x.results || [])).catch(e => setError(e.message)); }, [saved.length]); if (error) return <p className="error">{error}</p>; if (!items) return <p className="loading">Loading saved homes…</p>; return <><section className="hero"><span className="eyebrow">YOUR SHORTLIST</span><h2>Saved homes</h2><p>{items.length ? 'Keep the places you love close.' : 'Save a listing to build your shortlist.'}</p></section><section className="grid">{items.map(item => <Card key={item.listing_id} item={item} saved onSave={onSave} onOpen={onOpen} />)}</section></>; }
function App() { const [session, setSession] = useState(getSession()), [tab, setTab] = useState('listings'), [saved, setSaved] = useState([]), [selected, setSelected] = useState(null); useEffect(() => { if (!session) return; request('favourites').then(x => setSaved((x.results || []).map(i => i.listing_id || i))).catch(() => {}); const id = location.pathname.match(/^\/listing\/([^/]+)$/)?.[1]; if (id) request(`listings/${encodeURIComponent(id)}`).then(setSelected).catch(() => {}); }, [session]); async function toggle(id) { try { if (saved.includes(id)) { await request(`favourites/${id}`, { method: 'DELETE' }); setSaved(saved.filter(x => x !== id)); } else { await request('favourites', { method: 'POST', body: JSON.stringify({ id }) }); setSaved([...saved, id]); } } catch (e) { alert(e.message); } } function open(item) { history.pushState({}, '', `/listing/${encodeURIComponent(item.listing_id)}`); setSelected(item); } function close() { history.pushState({}, '', '/'); setSelected(null); } function logout() { localStorage.removeItem(sessionKey); setSession(null); } if (!session) return <Login onLogin={setSession} />; return <><header><a className="brand" onClick={() => { close(); setTab('listings'); }}>ivy<span>.</span>homes</a><nav>{[['listings','Buy'],['rentals','Rent'],['projects','Projects'],['insights','Insights']].map(([id,label]) => <button className={tab === id ? 'active' : ''} onClick={() => { close(); setTab(id); }}>{label}</button>)}</nav><div><button className="saved" onClick={() => { close(); setTab('saved'); }}>Saved {saved.length ? `(${saved.length})` : ''}</button><button className="logout" onClick={logout}>Sign out</button></div></header><main className="app">{selected ? <Detail item={selected} close={close} saved={saved.includes(selected.listing_id)} onSave={toggle} /> : tab === 'insights' ? <Insights /> : tab === 'saved' ? <Saved saved={saved} onSave={toggle} onOpen={open} /> : <Browse kind={tab} saved={saved} onSave={toggle} onOpen={open} />}</main></>; }
createRoot(document.getElementById('root')).render(<App />);
